name: gcloud command
description: execute the provided subcommand on gcloud

runs:
  using: node16
  main: action.js

inputs:
  subcommand:
    required: true
    description: the gcloud subcommand to execute
  command:
    required: false
    description: the gcloud command to execute
    default: beta compute
  expect_failure:
    required: false
    description: the action is supposed to succeed on failure and fail on success
    default: 'false'
  expect_output:
    required: false
    description: the output should not be empty
    default: 'true'
  location:
    required: false
    description: the location of the gcloud command
    default: ''
  location_name:
    required: false
    description: the parameter name that accesses the location
    default: ''
  zone:
    required: false
    description: the zone of the gcloud command
    default: ''
  zone_name:
    required: false
    description: the parameter name that accesses the zone
    default: ''

outputs:
  result:
    description: the resulting json of the executed command
