name: backup

on: workflow_dispatch

concurrency: github

jobs:
  check:
    name: check instance
    uses: ./.github/workflows/gcloud.yml
    secrets: inherit
    permissions:
      contents: read
      id-token: write
    with:
      subcommand: instances describe gh-ubuntu-22 --zone=${{ vars.ZONE }}

  backup:
    name: backup instance
    needs: check
    uses: ./.github/workflows/gcloud.yml
    secrets: inherit
    permissions:
      contents: read
      id-token: write
    with:
      subcommand: machine-images create gh-ubuntu-22-r${{ github.run_number }}
        --source-instance=gh-ubuntu-22
        --source-instance-zone=${{ vars.ZONE }}
        --storage-location=${{ vars.LOCATION }}
        --description="GitHub Runner on Ubuntu 22.04 LTS"
