name: backup

on: workflow_dispatch

concurrency: github

jobs:
  check:
    name: check instance
    uses: ./.github/workflows/gcloud.yml
    secrets: inherit
    permissions:
      contents: read
      id-token: write
    with:
      subcommand: instances describe gh-ubuntu-22 --zone=europe-north1-b

  delete:
    name: delete existing machine image
    needs: check
    uses: ./.github/workflows/gcloud.yml
    secrets: inherit
    permissions:
      contents: read
      id-token: write
    with:
      subcommand: machine-images delete gh-ubuntu-22

  backup:
    name: backup instance
    needs:
      - check
      - delete
    uses: ./.github/workflows/gcloud.yml
    secrets: inherit
    permissions:
      contents: read
      id-token: write
    with:
      subcommand: machine-images create gh-ubuntu-22-${{ dateFormat(now(), 'YYMMDDHHmm') }}
        --source-instance=gh-ubuntu-22
        --source-instance-zone=europe-north1-b
        --storage-location=europe-north1
        --description="GitHub Runner on Ubuntu 22.04 LTS"
