name: backup

on: workflow_dispatch

concurrency: github

jobs:
  check:
    name: check instance
    uses: ./.github/workflows/gcloud.yml
    secrets: inherit
    permissions:
      contents: read
      id-token: write
    with:
      zone_param: zone
      subcommand: instances describe ${{ vars.INSTANCE }}

  backup:
    name: backup instance
    needs: check
    uses: ./.github/workflows/gcloud.yml
    secrets: inherit
    permissions:
      contents: read
      id-token: write
    with:
      location_param: storage-location
      zone_param: source-instance-zone
      subcommand: machine-images create ${{ vars.INSTANCE }}-r${{ github.run_number }}
        --source-instance=${{ vars.INSTANCE }}
        --description="GitHub Runner on ${{ vars.SYSTEM_DESCRIPTION }}"
