name: cleanup

on:
  workflow_call:
    inputs:
      language:
        required: true
        description: runner label that identifies the installed language-specific tools
        type: string

concurrency: github-${{ inputs.language }}

jobs:
  cleanup:
    name: ${{ inputs.language }} runner tools
    defaults:
      run:
        shell: bash
    permissions:
      contents: none
    runs-on:
      - self-hosted
      - provider
      - ${{ inputs.language }}
    environment: provider
    steps:
      - name: delete temporary files in the action runner tools path
        run: |
          find /actions-runner/_diag -type f -mmin +5 -delete || true
          rm -rfv /actions-runner/_work/_tool/*
          rm -rfv /actions-runner/_work/_actions/*
      - name: check out repository
        uses: actions/checkout@v3.5.3
      - name: set up latest Node.js LTS
        uses: actions/setup-node@v4.0.0
        with:
          node-version: lts/Hydrogen
          cache: npm
      - name: install node dependencies
        run: npm ci
      - name: clean up old bin tools
        uses: ./cleanup
        with:
          prefix: bin
      - name: clean up old externals tools
        uses: ./cleanup
        with:
          prefix: externals
