name: create

on: workflow_dispatch

concurrency: github

jobs:
  check-instance:
    name: check instance availability
    uses: ./.github/workflows/gcloud.yml
    secrets: inherit
    permissions:
      contents: read
      id-token: write
    with:
      zone_param: zone
      subcommand: instances describe ${{ vars.INSTANCE }}
      expect_failure: true

  check-backup:
    name: check backup availability
    uses: ./.github/workflows/gcloud.yml
    secrets: inherit
    permissions:
      contents: read
      id-token: write
    with:
      subcommand: machine-images list
        --limit=1
        --sort-by=~name
        --filter=${{ vars.INSTANCE }}-r

  create:
    name: create instance
    needs:
      - check-instance
      - check-backup
    uses: ./.github/workflows/gcloud.yml
    secrets: inherit
    permissions:
      contents: read
      id-token: write
    with:
      zone_param: zone
      subcommand: instances create ${{ vars.INSTANCE }}
        --machine-type=t2d-standard-4
        --network-interface=network-tier=PREMIUM,stack-type=IPV4_ONLY,subnet=default
        --no-restart-on-failure
        --maintenance-policy=TERMINATE
        --provisioning-model=SPOT
        --instance-termination-action=STOP
        --max-run-duration=7200s
        --min-cpu-platform=Automatic
        --shielded-secure-boot
        --shielded-vtpm
        --shielded-integrity-monitoring
        --labels=goog-ec-src=vm_add-gcloud
        --reservation-affinity=any
        --key-revocation-action-type=stop
        --source-machine-image=${{ fromJSON(needs.check-backup.outputs.result)[0].name }}
