name: gcloud

on:
  workflow_call:
    inputs:
      subcommand:
        required: true
        type: string
    outputs:
      result:
        description: the supported versions within specified days
        value: ${{ jobs.execute.outputs.result }}

jobs:
  execute:
    name: execute compute job
    environment: google cloud
    defaults:
      run:
        shell: bash
    permissions:
      contents: read
      id-token: write
    outputs:
      result: ${{ steps.command.outputs.result }}
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v3.5.3
      - id: auth
        name: authenticate to Google Cloud
        uses: google-github-actions/auth@v1.1.1
        with:
          workload_identity_provider: ${{ secrets.ID_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - name: set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.1.1
        with:
          skip_install: true
          version: ''
          project_id: github-matfax
      - name: execute gcloud compute job
        id: command
        run: |
          RESULT=$(gcloud compute ${{ inputs.subcommand }} --format="json") ; STATUS=$?
          if [[ $STATUS -ne 0 ]]; then
            echo "Error running gcloud command"
            exit $STATUS
          fi
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "result<<$EOF" >> "$GITHUB_OUTPUT"
          echo "$RESULT" >> "$GITHUB_OUTPUT"
          echo "$EOF" >> "$GITHUB_OUTPUT"
