name: gcloud

on:
  workflow_call:
    inputs:
      subcommand:
        required: true
        type: string
      command:
        required: false
        type: string
        default: compute
    outputs:
      result:
        description: the supported versions within specified days
        value: ${{ jobs.execute.outputs.result }}

jobs:
  execute:
    name: execute ${{ inputs.command }} job
    environment: google cloud
    defaults:
      run:
        shell: bash
    permissions:
      contents: read
      id-token: write
    outputs:
      result: ${{ steps.command.outputs.stdout }}
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v3.5.3
      - id: auth
        name: authenticate to Google Cloud
        uses: google-github-actions/auth@v1.1.1
        with:
          workload_identity_provider: ${{ secrets.ID_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - name: set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.1.1
        with:
          skip_install: true
          version: ''
          project_id: github-matfax
      - name: execute gcloud ${{ inputs.command }} job
        uses: maddog2050/executable-wrapper@v1.0.9
        id: command
        continue-on-error: true
        with:
          run_command: gcloud ${{ inputs.command }} ${{ inputs.subcommand }} --quiet --format="json"
      - name: escalate error message if error occured
        if: steps.command.outputs.exitcode != '0'
        uses: actions/github-script@v6.4.1
        with:
          script: core.setFailed(steps.command.outputs.stderr.split('\n').pop())
