name: gcloud

on:
  workflow_call:
    inputs:
      subcommand:
        required: true
        type: string
      command:
        required: false
        type: string
        default: compute
    outputs:
      result:
        description: the supported versions within specified days
        value: ${{ jobs.execute.outputs.result }}

jobs:
  execute:
    name: execute ${{ inputs.command }} job
    environment: google cloud
    defaults:
      run:
        shell: bash
    permissions:
      contents: read
      id-token: write
    outputs:
      result: ${{ steps.command.outputs.stdout }}
      credentials_file: ${{ (inputs.credentials_file == '' || steps.restore.outputs.cache-hit != 'true') && steps.credentials_filename.outputs.filename || inputs.credentials_file }}
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v3.5.3
      - id: auth
        name: authenticate to Google Cloud
        uses: google-github-actions/auth@v1.1.1
        with:
          workload_identity_provider: ${{ secrets.ID_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - name: set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.1.1
        with:
          skip_install: true
          version: ''
          project_id: github-matfax
      - name: set up Node.js
        uses: actions/setup-node@v3.7.0
        with:
          node-version: lts/Hydrogen
          cache: npm
      - name: install node dependencies
        run: npm ci
      - name: execute gcloud ${{ inputs.command }} job
        uses: actions/github-script@v6.4.1
        with:
          script: |
            const { parseArgsStringToArgv } = require('string-argv')
            const commandArgs = parseArgsStringToArgv('${{ inputs.command }}')
            const subCommandArgs = parseArgsStringToArgv('${{ inputs.subcommand }}')
            const output = await exec.getExecOutput('gcloud', [...commandArgs, ...subCommandArgs, '--quiet', '--format="json"'])
            if (output.exitCode !== 0) {
                const splitErr = output.stderr.split('\n')
                core.setFailed(splitErr[splitErr.length - 3])
            }
