name: golang tool cache

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/golang.yml'
  workflow_dispatch:
  schedule:
    - cron: '5 8 * * *'

jobs:
  prepare:
    uses: ./.github/workflows/prepare.yml
    permissions:
      contents: none
    with:
      language: go

  update:
    name: update golang ${{ matrix.golang-version }}
    needs: prepare
    environment: provider
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: [self-hosted, provider]
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        golang-version: ${{ fromJson(needs.prepare.outputs.versions) }}
    steps:
      - name: check out repository
        uses: actions/checkout@v3.5.3
      - name: setting up golang ${{ matrix.golang-version }}
        uses: actions/setup-go@v4.0.1
        with:
          go-version: ${{ matrix.golang-version }}
          check-latest: true
      - name: initialize CodeQL
        uses: github/codeql-action/init@v2.20.4
        with:
          languages: go
