name: maintenance

on:
  workflow_dispatch:
    inputs:
      language:
        required: true
        description: identity of the runner label and codeQL language
        type: string

concurrency: github-${{ inputs.language }}

jobs:
  clean:
    name: clean up ${{ inputs.language }} runner
    permissions:
      contents: none
    runs-on:
      - self-hosted
      - provider
      - ${{ inputs.language }}
    environment: provider
    defaults:
      run:
        shell: bash
    steps:
      - name: delete temporary files in the actions-runner path
        run: |
          find /actions-runner/_diag -type f -mmin +5 -delete || true
          rm -rfv /actions-runner/_work/_tool/*
          rm -rfv /actions-runner/_work/_actions/*
      - name: clear user cache
        run: |
          find ~/.cache/*/* -mmin +5 -delete || true
      - name: clear user lib
        run: |
          rm -rfv ~/.local/lib
      - name: clear go cache
        if: inputs.language == 'go'
        run: |
          rm -rfv ~/go
      - name: clear bash history
        run: |
          rm -rfv ~/.bash_history

  patch:
    name: initiate patch job on ${{ inputs.language }} runner
    needs: clean
    uses: ./.github/workflows/gcloud.yml
    secrets: inherit
    permissions:
      contents: read
      id-token: write
    with:
      subcommand: os-config patch-jobs execute \
        --instance-filter-names=zones/europe-north1-b/instances/gh-${{ inputs.language }}-ubuntu-22 \
        --display-name=gh-${{ inputs.language }}-ubuntu-22-apt-upgrade \
        --duration=3600s \
        --reboot-config=default \
        --rollout-mode=zone-by-zone \
        --rollout-disruption-budget-percent=25 \
        --description="apt upgrade on GitHub Runner Ubuntu 22.04 LTS with ${{ inputs.language }} tools"

  update:
    name: update snaps on ${{ inputs.language }} runner
    needs: patch
    permissions:
      contents: none
    runs-on:
      - self-hosted
      - provider
      - ${{ inputs.language }}
    environment: provider
    defaults:
      run:
        shell: bash
    steps:
      - name: update nodejs snap
        run: |
          sudo snap refresh node --classic
