name: maintenance

on: workflow_dispatch

concurrency: github

jobs:
  patch:
    name: initiate cleanup and patching
    uses: ./.github/workflows/gcloud.yml
    secrets: inherit
    permissions:
      contents: read
      id-token: write
    with:
      subcommand: os-config patch-jobs execute
        --instance-filter-names=zones/europe-north1-b/instances/gh-ubuntu-22
        --display-name=gh-ubuntu-22-upgrade
        --duration=3600s
        --reboot-config=default
        --rollout-mode=zone-by-zone
        --rollout-disruption-budget-percent=25
        --description="software update and cleanup on GitHub Runner Ubuntu 22.04 LTS"
        --pre-patch-linux-executable=/opt/updates/cleanup
        --post-patch-linux-executable=/opt/updates/snap

  verify:
    name: verify patching status
    needs: patch
    permissions:
      contents: none
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - name: fail if patching job didn't succeed
        if: fromJSON(needs.patch.outputs.result).state != "SUCCEEDED"
        uses: actions/github-script@v6.4.1
        with:
          script: core.setFailed("patch job failed with status ${{ fromJSON(needs.check.outputs.result).state }}")
