name: maintenance

on:
  workflow_dispatch:
    inputs:
      language:
        required: true
        description: identity of the runner label and codeQL language
        type: string

concurrency: github-${{ inputs.language }}

jobs:
  clean:
    name: clean cache on ${{ matrix.language }}
    permissions:
      contents: none
    runs-on:
      - self-hosted
      - provider
      - ${{ inputs.language }}
    environment: provider
    defaults:
      run:
        shell: bash
    steps:
      - name: delete temporary files in the actions-runner path
        run: |
          rm -rfv /actions-runner/_*
      - name: clear user cache
        run: |
          rm -rfv ~/.cache/*
      - name: clear user lib
        run: |
          rm -rfv ~/.local/lib
      - name: clear go cache
        if: inputs.language == 'go'
        run: |
          rm -rfv ~/go
  update:
    name: update snaps on ${{ inputs.language }}
    permissions:
      contents: none
    runs-on:
      - self-hosted
      - provider
      - ${{ inputs.language }}
    environment: provider
    defaults:
      run:
        shell: bash
    steps:
      - name: update nodejs snap
        run: |
          sudo snap refresh node --classic
  patch:
    name: initiate patch job on ${{ inputs.language }}
    uses: ./.github/workflows/gcloud.yml
    with:
      subcommand: os-config patch-jobs execute --instance-filter-names=zones/europe-north1-b/instances/gh-${{ inputs.language }}-ubuntu-22 --display-name=gh-${{ inputs.language }}-ubuntu-22-apt-upgrade --duration=3600s --reboot-config=default --rollout-mode=zone-by-zone --rollout-disruption-budget-percent=25 --description="apt upgrade on GitHub Runner Ubuntu 22.04 with ${{ inputs.language }} tools"
