name: maintenance

on: workflow_dispatch

concurrency: github

jobs:
  patch:
    name: initiate cleanup and patching
    uses: ./.github/workflows/gcloud.yml
    secrets: inherit
    permissions:
      contents: read
      id-token: write
    with:
      zone_param: instance-filter-zones
      subcommand: os-config patch-jobs execute
        --instance-filter-name-prefixes=${{ vars.INSTANCE }}
        --display-name=${{ vars.INSTANCE }}-upgrade
        --duration=600s
        --reboot-config=default
        --rollout-mode=zone-by-zone
        --rollout-disruption-budget-percent=25
        --description="software update and cleanup on ${{ vars.SYSTEM_DESCRIPTION }}"
        --post-patch-linux-executable=/opt/updates/snap

  verify:
    name: verify patching status
    needs: patch
    permissions:
      contents: none
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - name: fail if patching job didn't succeed
        if: fromJSON(needs.patch.outputs.result).state != 'SUCCEEDED'
        uses: actions/github-script@v6.4.1
        with:
          script: core.setFailed("patch job failed with status ${{ fromJSON(needs.check.outputs.result).state }}")
