name: nodejs tool cache

on: workflow_dispatch

concurrency: github

jobs:
  prepare:
    uses: ./.github/workflows/prepare.yml
    permissions:
      contents: none
    with:
      language: nodejs
      cache-subdir: node

  update:
    name: update
    needs: prepare
    environment: provider
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on:
      - self-hosted
      - provider
      - nodejs
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        node-version: ${{ fromJson(needs.prepare.outputs.versions) }}
    steps:
      - name: check out repository
        uses: actions/checkout@v3.5.3
      - name: setting up nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v3.7.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: initialize CodeQL
        uses: github/codeql-action/init@v2.21.7
        with:
          languages: javascript
