name: python tool cache

on: workflow_dispatch

concurrency: github

jobs:
  prepare:
    uses: ./.github/workflows/prepare.yml
    permissions:
      contents: none
    with:
      language: python
      cache-subdir: Python

  update:
    name: update python ${{ matrix.python-version }}
    needs: prepare
    environment: provider
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on:
      - self-hosted
      - provider
      - python
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        python-version: ${{ fromJson(needs.prepare.outputs.versions) }}
    steps:
      - name: check out repository
        uses: actions/checkout@v3.5.3
      - name: install poetry from PyPI
        uses: install-pinned/poetry@b9aee499ab9d8a7cc8698e74933a82eb7d87373e  # 1.5.1
      - name: setting up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4.7.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: initialize CodeQL
        uses: github/codeql-action/init@v2.21.2
        with:
          languages: python
