name: schedule maintenance

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:
  workflow_run:
    workflows:
      - create
      - maintain
      - backup
      - delete
    types:
      - completed

concurrency: scheduler

jobs:
  invoke:
    name: invoke ${{ matrix.workflow }}
    permissions:
      contents: write
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        include:
          - trigger: none
            workflow: create
          - trigger: create
            workflow: maintain
          - trigger: maintain
            workflow: backup
          - trigger: backup
            workflow: delete
    if: (github.event_name != 'workflow_run' || github.event.workflow_run.event == 'repository_dispatch' && github.event.workflow_run.conclusion == 'success') && (github.event_name != 'workflow_run' && matrix.trigger == 'none' || github.event.workflow_run.workflow.id == matrix.trigger)
    steps:
      - name: dispatch scheduled event
        uses: peter-evans/repository-dispatch@v2.1.2
        with:
          event-type: scheduled-${{ matrix.workflow }}
          client-payload: '{"sha": "${{ github.event_name == 'workflow_run' && github.event.workflow_run.payload.sha || github.sha }}"}'
