name: schedule maintenance

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:
  workflow_run:
    workflows:
      - create
      - maintain
      - backup
      - delete
    types:
      - completed

concurrency: scheduler

jobs:
  invoke:
    name: invoke ${{ matrix.graphs.workflow }}
    permissions:
      actions: write
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        graphs: [
          { trigger: "none", workflow: "create" },
          { trigger: "create", workflow: "maintain" },
          { trigger: "maintain", workflow: "backup" },
          { trigger: "backup", workflow: "delete" }
        ]
    if: (github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success') && (github.event_name != 'workflow_run' && matrix.graphs.trigger == 'none' || contains(github.event.workflow_run.workflow.path, matrix.graphs.trigger))
    steps:
      - name: dispatch ${{ matrix.graphs.workflow }} workflow
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          workflow: ${{ matrix.graphs.workflow }}.yml
