name: schedule maintenance

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:
  workflow_run:
    branches:
      - main
    workflows:
      - create
      - maintain
      - backup
      - delete
    types:
      - completed

concurrency: scheduler

jobs:
  check:
    name: check conditions
    environment: scheduler
    permissions:
      contents: none
    runs-on: ubuntu-latest
    outputs:
      workflows: ${{ steps.filtered.outputs.json }}
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'
    steps:
      - name: set up graph
        id: graph
        uses: nickofthyme/object-remap@v2.0.0
        with:
          none: '["create"]'
          create: '["maintain"]'
          maintain: '["backup"]'
          backup: '["delete"]'
      - name: filter graph
        id: filtered
        uses: nickofthyme/object-remap@v2.0.0
        with:
          workflow: ${{ toJson(fromJson(steps.graph.outputs.json)[github.event_name != 'workflow_run' && 'none' || github.event.workflow_run.name]) }}

  meta:
    name: get meta data
    environment: scheduler
    runs-on: ubuntu-latest
    permissions:
      actions: read
    if: github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Enrich Workflow Run Event
        uses: pl-strflt/rich-workflow-run@v1.0.0
        id: workflow-run
        with:
          jobs-url: ${{ github.event.workflow_run.jobs_url }}
          logs-url: ${{ github.event.workflow_run.logs_url }}
      - name: Print information about the workflow run jobs
        run: echo "${{ steps.download-info.outputs.jobs }}"
      - name: Print information about the workflow run logs
        run: echo "${{ steps.download-info.outputs.logs }}"

  invoke:
    name: invoke ${{ matrix.workflow }}
    environment: scheduler
    needs: check
    permissions:
      contents: write
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.check.outputs.workflows) }}
    steps:
      - uses: marocchino/action-workflow_run-status@4d066ae9d73b3eb68ad4597e7fc612ddc6216dfc
        if: github.event_name == 'workflow_run'
      - name: dispatch ${{ matrix.workflow }} workflow
        uses: peter-evans/repository-dispatch@v2.1.2
        with:
          event-type: scheduled-${{ matrix.workflow }}
          client-payload: |
            {
              "ref": "${{ github.event_name == 'workflow_run' && github.event.workflow_run.ref || github.ref }}",
              "sha": "${{ github.event_name == 'workflow_run' && github.event.workflow_run.sha || github.sha }}"
            }
