name: schedule maintenance

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:
  workflow_run:
    workflows:
      - create
      - maintain
      - backup
      - delete
    types:
      - completed

concurrency: scheduler

jobs:
  invoke:
    name: invoke ${{ matrix.workflow }}
    permissions:
      actions: write
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        include:
          - trigger: none
            workflow: create
          - trigger: create
            workflow: maintain
          - trigger: maintain
            workflow: backup
          - trigger: backup
            workflow: delete
    if: (github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success') && (github.event_name != 'workflow_run' && matrix.trigger == 'none' || contains(github.event.workflow_run.workflow.path, matrix.trigger))
    steps:
      - name: dispatch ${{ matrix.workflow }} workflow
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          workflow: ${{ matrix.workflow }}.yml
