name: schedule maintenance

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:
  workflow_run:
    branches:
      - main
    workflows:
      - create
      - maintain
      - backup
      - delete
    types:
      - completed

concurrency: scheduler

jobs:
  check:
    name: check conditions
    environment: scheduler
    permissions:
      contents: none
    runs-on: ubuntu-latest
    outputs:
      workflows: ${{ steps.filtered.outputs.json }}
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'
    steps:
      - name: set up graph
        id: graph
        uses: nickofthyme/object-remap@v2.0.0
        with:
          none: '["create"]'
          create: '["maintain"]'
          maintain: '["backup"]'
          backup: '["delete"]'
      - name: filter graph
        id: filtered
        uses: nickofthyme/object-remap@v2.0.0
        with:
          workflow: ${{ toJson(fromJson(steps.graph.outputs.json)[github.event_name != 'workflow_run' && 'none' || github.event.workflow_run.name]) }}

  invoke:
    name: invoke ${{ matrix.workflow }}
    environment: scheduler
    needs: check
    permissions:
      actions: write
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.check.outputs.workflows) }}
    steps:
      - name: dispatch ${{ matrix.workflow }} workflow
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          workflow: ${{ matrix.workflow }}.yml
          #ref: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.ref || github.ref }}
